# Generated by config_brpc.sh, don't modify manually
SYSTEM=Linux
HDRS=/usr/include/
LIBS=/usr/lib64
PROTOC=/usr/bin/protoc
PROTOBUF_HDR=/usr/include/
CC=gcc
CXX=g++
GCC_VERSION=100201
STATIC_LINKINGS=
DYNAMIC_LINKINGS=-lpthread -lssl -lcrypto -ldl -lz -lrt -lgflags -lprotobuf -lleveldb -ljsoncpp -luuid
CPPFLAGS=-DBRPC_WITH_GLOG=0 -DGFLAGS_NS=gflags
ifeq ($(NEED_LIBPROTOC), 1)
    DYNAMIC_LINKINGS+=-lprotoc
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    DYNAMIC_LINKINGS+=-ltcmalloc_and_profiler
endif
ifeq ($(NEED_GTEST), 1)
    DYNAMIC_LINKINGS+=-lgtest
    DYNAMIC_LINKINGS+=-lgtest_main
endif
